name: Compile typst

on:
  - push

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # V27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix run .#build
    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: Compiled Slide
        path: main.pdf
